$(document).ready(function(){
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:15,
    autoplay:true,
    nav:false,
    dots:false,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
});
